# Generated by Django 4.1.3 on 2022-12-02 19:01

from django.db import migrations
import django.db.models.deletion
import info_restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_restaurant', '0004_alter_category_menu_alter_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='info_restaurant.menu'),
        ),
    ]
